"""create_tables

Revision ID: 0001
Revises:
Create Date: 2026-07-27 16:06:45.931249

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "history_wallets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid_user", sa.UUID(), nullable=False),
        sa.Column(
            "transaction_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("transaction_type", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("comment", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_history_wallets_uuid_user"),
        "history_wallets",
        ["uuid_user"],
        unique=False,
    )
    op.create_table(
        "wallets_users",
        sa.Column("uuid_user", sa.UUID(), nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("balance", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("uuid_user"),
        sa.UniqueConstraint("number"),
    )
    op.create_index(
        op.f("ix_wallets_users_uuid_user"), "wallets_users", ["uuid_user"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wallets_users_uuid_user"), table_name="wallets_users")
    op.drop_table("wallets_users")
    op.drop_index(op.f("ix_history_wallets_uuid_user"), table_name="history_wallets")
    op.drop_table("history_wallets")
    # ### end Alembic commands ###
