"""create_tables

Revision ID: 0001
Revises:
Create Date: 2026-07-27 16:06:38.899427

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cart_products_cache",
        sa.Column("uuid_product", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("sale", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("image_url", sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint("uuid_product"),
    )
    op.create_index(
        op.f("ix_cart_products_cache_uuid_product"),
        "cart_products_cache",
        ["uuid_product"],
        unique=True,
    )
    op.create_table(
        "carts_users",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("uuid_user", sa.UUID(), nullable=False),
        sa.Column("uuid_product", sa.UUID(), nullable=False),
        sa.Column("count_product", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_carts_users_uuid_user"), "carts_users", ["uuid_user"], unique=False
    )
    op.create_table(
        "orders_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid_user", sa.UUID(), nullable=False),
        sa.Column(
            "status_order",
            sa.Enum(
                "PENDING",
                "CREATED",
                "PROCESSING",
                "SHIPPED",
                "DELIVERED",
                "CANCELLED",
                name="order_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("status_payment", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("total_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("items", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_users_id"), "orders_users", ["id"], unique=False)
    op.create_index(
        op.f("ix_orders_users_uuid_user"), "orders_users", ["uuid_user"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_users_uuid_user"), table_name="orders_users")
    op.drop_index(op.f("ix_orders_users_id"), table_name="orders_users")
    op.drop_table("orders_users")
    op.drop_index(op.f("ix_carts_users_uuid_user"), table_name="carts_users")
    op.drop_table("carts_users")
    op.drop_index(
        op.f("ix_cart_products_cache_uuid_product"), table_name="cart_products_cache"
    )
    op.drop_table("cart_products_cache")
    # ### end Alembic commands ###
